id: ENVIRONMENT
type: BIOME
abstract: true

minecraft:
  colors:
    fog: 0x000000
    water: 0x62529E
    water-fog: 0x62529E
    sky: 0x000000
    grass: 0x8EB971
    foliage: 0x71A74D
  
  climate:
    precipitation: none
    temperature: 0.5
    downfall: 0.5